/**
 * PDF Export Utility
 * Generates PDF reports for athlete analysis
 * 
 * Note: Requires jsPDF library
 * Install with: npm install jspdf
 */

export const exportAthleteToPDF = (athlete, metrics, statistics) => {
  // This is a placeholder - actual implementation requires jsPDF
  // For now, create a simple text-based export
  
  const content = generateTextReport(athlete, metrics, statistics);
  
  // Create a downloadable text file for now
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `FreakForge-${athlete.firstName}-${athlete.lastName}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const generateTextReport = (athlete, metrics, statistics) => {
  const exceptionalMetrics = metrics.filter(m => Math.abs(m.sigma) >= 1.5);
  
  let report = `
╔═══════════════════════════════════════════════════════════════╗
║                     FREAKFORGE ANALYSIS                       ║
║                  Athlete Performance Report                   ║
╚═══════════════════════════════════════════════════════════════╝

ATHLETE INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Name:         ${athlete.firstName} ${athlete.lastName}
Position:     ${athlete.position}
State:        ${athlete.state}
Class:        ${athlete.gradYear}

STANDARD METRICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
40-Yard Dash:     ${athlete.dash40 ? athlete.dash40.toFixed(2) + ' sec' : 'N/A'}
Vertical Jump:    ${athlete.verticalJump ? athlete.verticalJump.toFixed(1) + ' in' : 'N/A'}
Broad Jump:       ${athlete.broadJump ? athlete.broadJump.toFixed(1) + ' in' : 'N/A'}
Pro Agility:      ${athlete.proAgility ? athlete.proAgility.toFixed(2) + ' sec' : 'N/A'}
L-Drill:          ${athlete.lDrill ? athlete.lDrill.toFixed(2) + ' sec' : 'N/A'}
Height:           ${athlete.height ? Math.floor(athlete.height / 12) + "'" + (athlete.height % 12) + '"' : 'N/A'}
Weight:           ${athlete.weight ? athlete.weight.toFixed(0) + ' lbs' : 'N/A'}

EXCEPTIONAL METRICS (|σ| ≥ 1.5)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Exceptional: ${exceptionalMetrics.length}
`;

  if (exceptionalMetrics.length > 0) {
    exceptionalMetrics.forEach((metric, index) => {
      const sigmaStr = metric.sigma > 0 ? `+${metric.sigma.toFixed(2)}` : metric.sigma.toFixed(2);
      report += `
${index + 1}. ${metric.formula}
   Value: ${typeof metric.value === 'number' ? metric.value.toFixed(3) : metric.value}
   Sigma: ${sigmaStr}σ
   Status: ${metric.sigma > 0 ? 'Above Average' : 'Below Average'}
`;
    });
  } else {
    report += `
No exceptional metrics found. All metrics within ±1.5σ of average.
`;
  }

  report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INTERPRETATION GUIDE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
±1.0σ - Above/Below Average (~84th percentile)
±1.5σ - Exceptional (~93rd percentile)
±2.0σ - Elite (~98th percentile)
±2.5σ - Freak (~99.4th percentile)
±3.0σ - Once in a Generation (~99.9th percentile)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by FreakForge - Athletic Performance Analysis
Report Date: ${new Date().toLocaleDateString()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

  return report;
};

// Future: Add actual PDF generation with jsPDF
/*
import jsPDF from 'jspdf';

export const exportAthleteToPDFWithGraphics = (athlete, metrics, canvasElement) => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(20);
  doc.text('FreakForge Analysis', 20, 20);
  
  // Add athlete info
  doc.setFontSize(12);
  doc.text(`${athlete.firstName} ${athlete.lastName}`, 20, 35);
  doc.text(`Position: ${athlete.position} | State: ${athlete.state}`, 20, 42);
  
  // Add canvas image if provided
  if (canvasElement) {
    const imgData = canvasElement.toDataURL('image/png');
    doc.addImage(imgData, 'PNG', 20, 50, 170, 80);
  }
  
  // Save
  doc.save(`FreakForge-${athlete.firstName}-${athlete.lastName}.pdf`);
};
*/
